// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWatchlistSymbol(arg1) {
  return window['go']['main']['App']['AddWatchlistSymbol'](arg1);
}

export function ConnectTws(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectTws'](arg1, arg2, arg3);
}

export function DisconnectTws() {
  return window['go']['main']['App']['DisconnectTws']();
}

export function ExportStrategyFile(arg1) {
  return window['go']['main']['App']['ExportStrategyFile'](arg1);
}

export function FailsafeStop() {
  return window['go']['main']['App']['FailsafeStop']();
}

export function GetCockpitState() {
  return window['go']['main']['App']['GetCockpitState']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetRuntimeState() {
  return window['go']['main']['App']['GetRuntimeState']();
}

export function GetStrategy() {
  return window['go']['main']['App']['GetStrategy']();
}

export function GetTWSConnection() {
  return window['go']['main']['App']['GetTWSConnection']();
}

export function GetWatchlist() {
  return window['go']['main']['App']['GetWatchlist']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportStrategyFile() {
  return window['go']['main']['App']['ImportStrategyFile']();
}

export function ImportTradingViewWatchlist(arg1) {
  return window['go']['main']['App']['ImportTradingViewWatchlist'](arg1);
}

export function RemoveWatchlistSymbol(arg1) {
  return window['go']['main']['App']['RemoveWatchlistSymbol'](arg1);
}

export function StartBot() {
  return window['go']['main']['App']['StartBot']();
}

export function StopBot() {
  return window['go']['main']['App']['StopBot']();
}

export function UpdateCockpitState(arg1) {
  return window['go']['main']['App']['UpdateCockpitState'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateStrategy(arg1) {
  return window['go']['main']['App']['UpdateStrategy'](arg1);
}

export function UpdateTWSConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTWSConnection'](arg1, arg2, arg3);
}
