// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddWatchlistSymbol(arg1:string):Promise<models.WatchlistResponse>;

export function ConnectTws(arg1:string,arg2:number,arg3:number):Promise<Record<string, any>>;

export function DisconnectTws():Promise<Record<string, any>>;

export function ExportStrategyFile(arg1:Record<string, any>):Promise<void>;

export function FailsafeStop():Promise<void>;

export function GetCockpitState():Promise<models.CockpitStateResponse>;

export function GetConfig():Promise<Record<string, any>>;

export function GetRuntimeState():Promise<models.BotState>;

export function GetStrategy():Promise<Record<string, any>>;

export function GetTWSConnection():Promise<Record<string, any>>;

export function GetWatchlist():Promise<models.WatchlistResponse>;

export function Greet(arg1:string):Promise<string>;

export function ImportStrategyFile():Promise<Record<string, any>>;

export function ImportTradingViewWatchlist(arg1:string):Promise<models.WatchlistResponse>;

export function RemoveWatchlistSymbol(arg1:string):Promise<models.WatchlistResponse>;

export function StartBot():Promise<Record<string, any>>;

export function StopBot():Promise<Record<string, any>>;

export function UpdateCockpitState(arg1:models.CockpitStateResponse):Promise<models.CockpitStateResponse>;

export function UpdateConfig(arg1:Record<string, any>):Promise<Record<string, any>>;

export function UpdateStrategy(arg1:Record<string, any>):Promise<Record<string, any>>;

export function UpdateTWSConnection(arg1:string,arg2:number,arg3:number):Promise<void>;
