// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWatchlistSymbol(arg1) {
  return window['go']['main']['App']['AddWatchlistSymbol'](arg1);
}

export function GetCockpitState() {
  return window['go']['main']['App']['GetCockpitState']();
}

export function GetWatchlist() {
  return window['go']['main']['App']['GetWatchlist']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportTradingViewWatchlist(arg1) {
  return window['go']['main']['App']['ImportTradingViewWatchlist'](arg1);
}

export function RemoveWatchlistSymbol(arg1) {
  return window['go']['main']['App']['RemoveWatchlistSymbol'](arg1);
}

export function UpdateCockpitState(arg1) {
  return window['go']['main']['App']['UpdateCockpitState'](arg1);
}
